apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-spark-demo
  namespace: sparkdemo02
spec:
  template:
    spec:
      containers:
        - name: kafka-spark-demo
          image: swapnil1994/sparkkakfkaregistry:latest
      restartPolicy: Never
