apiVersion: v1
kind: Pod
metadata:
  name: kafka-consumer
  namespace: sparkdemo02
spec:
  containers:
  - name: kafka-consumer
    image: quay.io/strimzi/kafka:0.40.0-kafka-3.7.0
    command: ["/bin/sh", "-c"]
    args: ["bin/kafka-console-consumer.sh --bootstrap-server my-cluster-kafka-bootstrap:9092 --topic my-topic --from-beginning"]
    stdin: true
    tty: true
  restartPolicy: Never
